name: base
mask_ratio: 0.75
patch_size: 16
dim: 768
depth: 12
num_heads: 12
decoder_embed_dim: 512
decoder_depth: 8
decoder_num_heads: 16
mlp_ratio: 4
norm_layer:
  _partial_: true
  _target_: torch.nn.LayerNorm
  eps: 1e-6