name: tiny
mask_ratio: 0.75
patch_size: 16
dim: 192
depth: 6
num_heads: 4
decoder_embed_dim: 256
decoder_depth: 4
decoder_num_heads: 4
mlp_ratio: 4
norm_layer:
  _partial_: true
  _target_: torch.nn.LayerNorm
  eps: 1e-6
