name: mae

learning_rate: 0.0003
image_size: 224

augmentations:

  train:
    
    # Random resized crop
    - _target_: torchvision.transforms.RandomResizedCrop
      size: ${model.image_size}
    
    # Horizontal flip
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 1.0
    
    # Convert to tensor
    - _target_: torchvision.transforms.ToTensor

    # # Normalization
    # - _target_: torchvision.transforms.Normalize
    #   mean: ${dataset.mean}
    #   std: ${dataset.std}

params:
  img_size: ${model.image_size}
  norm_pix_loss: true
  warmup_epochs: 10
  min_learning_rate: 0
